@startuml

title __MTBDD_NEW's Class Diagram__\n

  namespace  {
    namespace TBDD {
      namespace NEW {
        class MTBDD_NEW.Converter {
            {static} + DT_into_MTBDD()
            {static} + MTBDD_into_DT()
        }
      }
    }
  }
  

  namespace  {
    namespace TBDD {
      namespace NEW {
        class MTBDD_NEW.MTBDD {
            - lastID : int
            - name : String
            - nodes : List<Node>
            - terminalNodesWithParents : Map<Integer, List<Integer>>
            + MTBDD()
            + addNode()
            + addParentToTerminalNode()
            + addTerminalNode()
            + existingTNodeID()
            + getHighID()
            + getLastID()
            + getLowID()
            + getName()
            + getNodes()
            + getTerminalNodesWithParents()
            + hasHighChild()
            + hasLowChild()
            + isMTBDDEmpty()
            + isTerminal()
            + setHighID()
            + setLastID()
            + setLowID()
            + toString()
        }
      }
    }
  }
  

  namespace  {
    namespace TBDD {
      namespace NEW {
        class MTBDD_NEW.Node {
            - highID : int
            - label : String
            - lowID : int
            + equals()
            + getHighID()
            + getLabel()
            + getLowID()
            + hashCode()
            {static} + initializeNode()
            + setHighID()
            + setLabel()
            + setLowID()
            + toString()
        }
      }
    }
  }
  

  namespace  {
    namespace TBDD {
      namespace NEW {
        class MTBDD_NEW.Run {
            {static} + main()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
