@startuml

title __DECISION_TABLE's Class Diagram__\n

  namespace  {
    namespace ecision_table {
      class decision_table.Action {
          - ID : int
          - name : String
          + Action()
          + compareTo()
          + equals()
          + getID()
          + getName()
          + hashCode()
          + setID()
          + setName()
          + toString()
      }
    }
  }
  

  namespace  {
    namespace ecision_table {
      class decision_table.Condition {
          - ID : int
          - name : String
          + Condition()
          + compareTo()
          + equals()
          + getID()
          + getName()
          + hashCode()
          + setID()
          + setName()
          + toString()
      }
    }
  }
  

  namespace  {
    namespace ecision_table {
      class decision_table.DTFileOutput {
          - dts : List<DecisionTable>
          - name : String
          + DTFileOutput()
          + DTFileOutput()
          - prepareDTinTextForm()
          - writeDTToFile()
          - writeDTsToFile()
      }
    }
  }
  

  namespace  {
    namespace ecision_table {
      class decision_table.DTFileReader {
          - path : String
          + DTFileReader()
          + getPath()
          + listOfPairLists()
          + setPath()
          - actionPairs()
          - changeOrder()
          - conditionPairs()
          - divideDTParts()
          - extractData()
          - splitData()
      }
    }
  }
  

  namespace  {
    namespace ecision_table {
      class decision_table.DecisionTable {
          - name : String
          - ruleList : List<Rule>
          + DecisionTable()
          + addPairToRule()
          + addPairToRule()
          + addRule()
          + addRule()
          + complementOtherRules()
          + complementOtherRulesAction()
          + complementOtherRulesCondition()
          + copyOfDecisionTable()
          + equals()
          + expandDT()
          + getDTFromFile()
          + getName()
          + getRuleList()
          + getWorkingActions()
          + isDTShortened()
          {static} + isRuleShortened()
          + setName()
          + setRuleList()
          + shortenDT()
          + toString()
      }
    }
  }
  

  namespace  {
    namespace ecision_table {
      class decision_table.Pair {
          - aBoolean : Boolean
          - value : Object
          + Pair()
          + compareTo()
          + copyOfPair()
          + equals()
          + getValue()
          + getaBoolean()
          + setValue()
          + setaBoolean()
          + toString()
      }
    }
  }
  

  namespace  {
    namespace ecision_table {
      class decision_table.Rule {
          - ID : int
          - actionPairs : List<Pair>
          - conditionPairs : List<Pair>
          + Rule()
          + addPair()
          + addPair()
          + addPairs()
          + compareActionPairs()
          + compareConditionPairs()
          + copyOfRule()
          + equals()
          + getActionPairs()
          + getConditionPairs()
          + getID()
          + setActionPairs()
          + setConditionPairs()
          + setID()
          + toString()
      }
    }
  }
  

  namespace  {
    namespace ecision_table {
      class decision_table.RunDT {
          {static} + main()
      }
    }
  }
  

  namespace  {
    namespace ecision_table {
      class decision_table.Utility {
          {static} + booleansCanMerge()
          {static} + combineRulesByAction()
          {static} + compareTwoBooleans()
          {static} + countTrues()
          {static} + distributeRule()
          {static} + extractUnusedItems()
          {static} + groupMappings()
          {static} + merge2Rules()
          {static} + multipleCountTrues()
          {static} + newIndicesCombination()
          {static} + rememberUsedRules()
          {static} + rulesCanMerge()
          {static} + stringToBoolean()
      }
    }
  }
  

  decision_table.Action .up.|> java.lang.Comparable
  decision_table.Condition .up.|> java.lang.Comparable
  decision_table.DTFileOutput o-- decision_table.DecisionTable : dt
  decision_table.Pair .up.|> java.lang.Comparable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
